<?php

return [
    'Person_Operation_*_sound',
    'Play_History_*',
    'Play_Times_sound_*',
    'Search_*',
    'asmr_link_*',
    'cuimian_link_*',
    'drama_link_*',
    'peiyin_link_*',
    '*VcodeTimes',
    'drama_jp_*',
    'illustration_*',
    'music_radio_*',
    'ysmh_*',
    'novel_link_*',
    'ysmh_link_*',
    'Play_Add_lock_*_sound_*',
    'illustration_*_ids',
    'package_key*',
    'quanzhi*',
    'voice*',
    'test*',
];
